import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ClerkProviderWrapper from "@/components/ClerkProviderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sensai - AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProviderWrapper>
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {/* {header} */}
          <main className="min-h-screen">{children}</main>
          {/* {footer} */}
          <footer className="bg-muted/50 py-12"><div className="container mx-auto px-4 text-center text-grey-200">Made With ❤️ By Yash Kalra
            </div></footer>
        </ThemeProvider> 
      </body>
    </html>
    </ClerkProviderWrapper>
  );
}
